Add gibbs steps for dispersion term
aesara-devs/aemcmc pull request #28
Opened 2022-04-21 04:10 UTC by xjing76

This PR will be adding Gibbs steps that would allow sampling for dispersion terms of Negative Binomial. 

This PR will follow the compound poisson method mentioned [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4180062/)

So far we roughy added the Gibbs steps for  
1. r -dispersion terms in N(r, p)
2. h - Inverse of scale parameter for gamma distribution of r
3. L_i - The number terms of L/N of a Poisson distributed variable in Compound Poisson distribution

The most tricky part so far comes form the sampling of L_i as it is a discrete sampling from a given probability vector where the probability vector comes from a pre-calculated matrix with some additional computation. 

Next step is to add `match` functions for the NB graph with dispersion terms.

2022-04-21 06:55 UTC, zoj613 commented
@xjing76 You might want to consider setting up `pre-commit` locally using the config file in this repo, Tests for the style check are currently failing.

2022-04-21 12:18 UTC, rlouf commented
Great! Following what @zoj613 said: could you install `pre-commit` and make sure that /every commit/ at least passes code checks, and to not start on a new commit until the current one passes the tests as well?

2022-04-25 14:18 UTC, xjing76 commented
I think I set up the main steps for the alpha gibbs sampler steps. 

1. However, I think I need a more simple way to calculate the pre-calculated matrix F  as the size of it is determined by the maximum of observations, and so the size of it can get quite large. 

2. I am still looking for ways to make this`srng.choice(range(N), size=1, replace=True, p=R_r(F, r, i)) for i in y` work as p seems cannot be assigned as a rv.

2022-04-26 13:09 UTC, xjing76 commented
> Great! For (2) could you provide a minimal example that illustrates the problem you're having so I can have a look?

I think the problem itself is not what I thought it was initially. But the problem still persist. 

1.  Initially i set up the sampling step as 

But it seems that I am not able to iterate through y (with a `can't determine dimension` error)
li = [srng.choice(at.arange(N), size=1, replace=True, p=R_r(F, r, i)) for i in y]

But base on the paper equation (23-25) we would need to sample `l_i` seperately for each new `r` and each `y_i`

2. Just to test out the technical feasibility of the set up, I did

li = srng.choice(at.arange(N), size=N, replace=True, p=R_r(F, r, 10)) 

This would not work as well as some step results p vector to be a vector full of `nan` 

Any suggestions how should I debug this?

2022-04-26 13:24 UTC, rlouf commented
Do you have a setup that allows you to work with a debugger such as [pdb](https://docs.python.org/3/library/pdb.html)? You should then be able to go up the stack trace when said line fails and investigate where these `NaN`s come from.

2022-04-26 13:59 UTC, xjing76 commented
> Do you have a setup that allows you to work with a debugger such as [pdb](https://docs.python.org/3/library/pdb.html)? You should then be able to go up the stack trace when said line fails and investigate where these `NaN`s come from.

I do have `--pdb` set up but the results are coming from graph op and there are more arguments than what we supply. I will take a further look into it. Thanks!

2022-04-28 12:23 UTC, xjing76 commented
1 On making `F` and `R_r` matrix numerically stable. However I didn't use the stirling method that was mentioned in [this paper](https://scholar.google.com/scholar?as_q=&as_epq=Augment-and-conquer%20negative%20binomial%20processes&as_occt=title&as_sauthors=Mingyuan+Zhou&as_ylo=2012&as_yhi=2012&as_sdt=1.&as_sdtp=on&as_sdtf=&as_sdts=22&) here (lemma 2.1) as Stirling number can get overflow pretty easily at 100. I just added as switch state as in the paper that when r > 1 we would use the unweighted `F` instead of weighted matrix `R_r`

2. Since `ChoiceRV` in Aesara only take a vector as a p, I am coming up with a `multichoiceRV` here (which is not working yet) to temporarily solve this issue. But I am hoping that we might eventually adding a `choiceRV` in aesara that would be able to handle such problem.

2022-04-28 14:42 UTC, rlouf commented on aemcmc/gibbs.py
> +class MultiChoiceRV(ChoiceRV):
Could you move this to `dist.py`?

2022-04-28 15:15 UTC, xjing76 commented on aemcmc/gibbs.py
> +class MultiChoiceRV(ChoiceRV):
Oh. of course.

2022-05-06 15:47 UTC, xjing76 commented
So far, I think the engineering for Multichoice RV are done. The shape and unit test are passing without much issue. However, it seems like the sampling step itself is converging. Looking at the samples for R, it keep getting larger and larger while the true dispersion term is only 1. It would be the next step for me.

2022-05-12 12:28 UTC, xjing76 commented
By only looking at `test_horseshoe_nbinom` the betas sampled in those set up are not converging very well either. So I set up a [separate branch](https://github.com/xjing76/aemcmc/tree/fixed_beta) with only given betas and allow only sampling for the dispersion parts. 

However, it seems like the dispersion portion is still converging to a very large number than what we preset to (1). I attempt to fully covert the code to the implementation of [matlab version](https://mingyuanzhou.github.io/Softwares/LGNB_Regression_v0.zip) yet i think still need some more time to figure out the model as the `phi` portion used in matlab is intertwined with the sampling of both beta and the dispersion `r`


https://github.com/xjing76/aemcmc/tree/fixed_beta

2022-05-13 00:05 UTC, brandonwillard requested changes
> I think it may not be enough just to have a test on the shape of the samples but also on the values of those sample results.

Yes, a solid set of unit tests for `sampling_for_li` are needed.

> By only looking at `test_horseshoe_nbinom` the betas sampled in those set up are not converging very well either. So I set up a [separate branch](https://github.com/xjing76/aemcmc/tree/fixed_beta) with only given betas and allow only sampling for the dispersion parts.
> 
> However, it seems like the dispersion portion is still converging to a very large number than what we preset to (1). I attempt to fully covert the code to the implementation of [matlab version](https://mingyuanzhou.github.io/Softwares/LGNB_Regression_v0.zip) yet i think still need some more time to figure out the model as the `phi` portion used in matlab is intertwined with the sampling of both beta and the dispersion `r`

To which values/output are you referring?  Ones from `test_horseshoe_nbinom_w_dispersion`?  I'm not able to get that test to run locally due to unresolved shape issues, and there aren't any results in CI with which to compare due to the `pre-commit` errors.

My guess is that the `MultiChoiceRV` implementation isn't finished.  There are definitely some important test cases missing, so the next step is to add some more thorough tests.

When we're confident that `MultiChoiceRV` is working as expected, we'll need to do the same for the distribution implemented by `sampling_for_li`.

2022-05-13 00:05 UTC, brandonwillard commented on tests/test_dists.py
> +    # breakpoint()
```suggestion
```

2022-05-13 00:05 UTC, brandonwillard commented on tests/test_dists.py
> +    assert np.alltrue(res1.eval() == res2.eval())
The graphs `res1` and `res2` are literally the same, no?  It's not clear what this `assert` is supposed to be testing, and, as the comment says, we absolutely need to confirm that this is working before considering the results of a model that uses this sampler.

2022-05-13 00:05 UTC, brandonwillard commented on tests/test_gibbs.py
> +    R_r(F, r_, 4)
This looks like an unfinished test. We definitely need a test for these components (i.e. everything involved in `sampling_for_li`, and that function itself), though.

2022-05-13 00:40 UTC, brandonwillard commented
> I attempt to fully covert the code to the implementation of [matlab version](https://mingyuanzhou.github.io/Softwares/LGNB_Regression_v0.zip) yet i think still need some more time to figure out the model as the `phi` portion used in matlab is intertwined with the sampling of both beta and the dispersion `r`

That implementation references M. Zhou and L. Carin, "Negative Binomial Process Count and Mixture Modeling,"  arXiv:1209.3442, Sept. 2012 and M. Zhou and L. Carin, "Augment-and-Conquer Negative Binomial Processes," in NIPS 2012.  The former uses the CRTP distribution formulation for `L_i`, instead of the computations you're using from Zhou M, Li L, Dunson D, Carin L. "Lognormal and Gamma Mixed Negative Binomial Regression", and the latter states that the CRTP distribution is a sum of CRT variates, and that CRT variates can be drawn as a sum of Bernoullis.

The CRTP approach looks much simpler, as the reference implementation demonstrates, so we should go with that one.

2022-05-25 18:49 UTC, xjing76 commented
Here I finally updated this branch with similar set up as with the matlab implementation. 

1 I set up a CRT_sum and the sampling step for dispersion term "r" almost exactly like that of in the matlab implementation. However, I kept the sampling step for `beta` the same way as it was before. 

2 Here is still quite some issues with the current set up. 
   - the steps do quite badly with any 0 impressions. I had to tune the toy data parameter to make sure all y are above zero. 
   - The sampling of `r` are making huge jumps between very large value e6 and very small values e-5, which is also one of the reason why the polygamma sampling is problematic  with impressions have zeros in them, as the `h` parameter, composed of `y+ r`. 
   - Technical wise the sampling step is doing okay with good speed and should be bug free however, the convergence is till not very ideal

2022-05-25 20:28 UTC, brandonwillard commented
Don't forget to resolve the open conversations once they've been addressed.

2022-05-26 00:40 UTC, brandonwillard requested changes
In general, it looks like you've adapted the reference Matlab code a bit too literally.  Extra terms have been introduced that appear to overlap with existing terms already handled by `horseshoe_step`.

It would really help to write clear docstrings for these new functions so that we can more easily see the mathematical assumptions.

2022-05-26 00:40 UTC, brandonwillard commented on aemcmc/gibbs.py
> +    phi = srng.gamma(1e-2 + T / 2, 1 / (1e-2 + at.sum(psi_beta * psi_beta) / 2), size=1)
These references to a $\psi$ term lead me to believe that these steps aren't specifically for the $r$ parameter, but other parts of the model that are already covered by the existing PG-based negative-binomial sampler.

That could very easily explain any issues you've seen with this implementation.

2022-05-26 00:40 UTC, brandonwillard commented on aemcmc/gibbs.py
> +    phi_rv = srng.gamma(1, 1, size=1)
What are these `phi*` terms?  Also, a sampling step for $r$ should only require the previous sample value of $r$ and the $\pi_i$ that make up $y_i \sim \operatorname{NB}\left(r, \pi_i\right)$.

2022-06-03 07:12 UTC, brandonwillard requested changes
Don't forget to resolve open conversations (that have been resolved via code changes).

2022-06-03 07:12 UTC, brandonwillard commented on tests/test_gibbs.py
> +    np.array(y_post).mean(0)
This looks like an unfinished line.

2022-06-03 07:12 UTC, brandonwillard commented on aemcmc/gibbs.py
> +) -> Tuple[TensorVariable, TensorVariable, TensorVariable]:
This still needs a docstring.

2022-06-03 07:21 UTC, brandonwillard requested changes
The rename of `h*` to `r*` should be in a separate commit.

2022-06-03 07:29 UTC, brandonwillard requested changes

2022-06-03 07:29 UTC, brandonwillard commented on aemcmc/gibbs.py
> +    Lsum = 0
```suggestion
    L_sum = 0
```

2022-06-03 07:29 UTC, brandonwillard commented on aemcmc/gibbs.py
> +        r_new = r_step(srng, r, p, a_0, h, y)
This `srng.gamma` is a fixed (hyper)prior assumption that we can't have baked into this sampler.  Instead, we want to let the user define their own models/(hyper)priors&mdash;and corresponding sample steps.
```suggestion
        r_new = r_step(srng, r, p, a_0, h, y)
```

2022-06-03 07:29 UTC, brandonwillard commented on aemcmc/gibbs.py
> +    ) -> Tuple[TensorVariable, TensorVariable, TensorVariable, TensorVariable]:
```suggestion
        a_0: TensorVariable,
        h: TensorVariable,
    ) -> Tuple[TensorVariable, TensorVariable, TensorVariable, TensorVariable]:
```

2022-06-03 07:29 UTC, brandonwillard commented on aemcmc/gibbs.py
> +    a_0, _ = gamma_prior_match(r_rv)
```suggestion
    a_0, h = gamma_prior_match(r_rv)
```

2022-06-03 07:29 UTC, brandonwillard commented on aemcmc/gibbs.py
> +        non_sequences=[y, X, a_0],
```suggestion
        non_sequences=[y, X, a_0, h],
```

2022-06-18 02:26 UTC, brandonwillard commented
The current failure is due the problem addressed in https://github.com/aesara-devs/aesara/pull/1003.

2022-06-19 22:09 UTC, brandonwillard approved these changes

2022-06-20 00:49 UTC, merged